### ISSUE TITLE
 SciMLTutorials install loop

### ISSUE THREAD

**Issue by BouarfaMahi** [SciML/SciMLTutorials.jl#479]
hi
How do you fix the SciMLTutorials install loop on julia 1.6.4?

**Comment by ChrisRackauckas** [comment]
What do you mean?

**Comment by BouarfaMahi** [comment]
here is the

 process, 

julia> SciMLTutorials.open_notebooks()
[ Info: Weaving /home/jupyter-quant/.julia/packages/SciMLTutorials/3xNR5/src/../tutorials/DiffEqUncertainty/01-expectation_introduction.jmd
┌ Info: Instantiating
└   folder = "DiffEqUncertainty"
  Activating environment at `~/.julia/packages/SciMLTutorials/3xNR5/tutorials/DiffEqUncertainty/Project.toml`
Precompiling project...
  ✓ JSON
  ✓ Tables
  ✓ Conda
  ✓ Mustache
  ✓ IJulia
  ✓ Weave
  ✓ SciMLTutorials
  94 dependencies successfully precompiled in 485 seconds (237 already precompiled)
  7 dependencies precompiled but different versions are currently loaded. Restart julia to access the new versions
    Building Random123 → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/7c6710c8198fd4444b5eb6a3840b7d47bd359
3c5/build.log`
    Building GR ───────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/011458b83178ac913dc4eb73b229af45bdde5
d83/build.log`
    Building Conda ────→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/299304989a5e6473d985212c28928899c74e9
421/build.log`
    Building IJulia ───→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/d8b9c31196e1dd92181cd0f5760ca2d2ffb4a
c0f/build.log`
Precompiling project...
  Progress [======>                                  ]  13/94
  ✓ JSON
  ✓ Tables
  ◓ LoopVectorization
  ◐ SpecialFunctions
  ✓ Conda
  ✓ Mustache
  ◓ TableOperations

with infinite loop

**Comment by ChrisRackauckas** [comment]
Are you sure it's infinite? The precompile of LoopVectorization can take awhile, but not infinite? Anyways, that's something to ask of those packages, LoopVectorization, SpecialFunctions, or TableOperations.jl. One of those is taking awhile to precompile on your machine, but that's not SciMLTutorials. Add them separately to isolate.

Closing this because there's nothing for SciMLTutorials.jl here, but feel free to continue asking questions.
